name: ema.blog
description: "Emanuele DelBono's blog"
url: http://ema.codiceplastico.com
markdown: kramdown
highlighter: rouge
auto: true
paginate: 5
paginate_path: "/page:num"
title: ema.blog
encoding: utf-8
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# Disqus Comments
disqus_short_name: emadb
disqus_show_comment_count: true
plugins: [jekyll-paginate]
